/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BookCancel.java
 *
 * Created on Jul 30, 2010, 8:59:54 PM
 */

/**
 *
 * @author megha
 */
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.*;
public class BookCancel extends javax.swing.JFrame {

    /** Creates new form BookCancel */
    int stayTime;
    int aMonth,dMonth;
    int aDay;
    int dDay;
    public BookCancel() {
        initComponents();
        BookingDetailsPart2Panel.setVisible(false);
        cancelBookingPanel.setVisible(false);
        EnterBookingDetailsPanel.setVisible(false);
        bookCancelOptionsPanel.setVisible(true);
        String m ="0";
        for(int i=1; i<=12; i++)
        {
           if(i>9)
              m="";
           Month.addItem(m+ i);
           Month1.addItem(m+ i);
        }
        ContinueBtn.setVisible(false);
        cancelBtn.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        bookCancelOptionsPanel = new javax.swing.JPanel();
        CancelBooking = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Booking = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cancelBookingPanel = new javax.swing.JPanel();
        continueBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        BookingNoTF = new javax.swing.JTextField();
        error1 = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        EnterBookingDetailsPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SearchBtn = new javax.swing.JButton();
        TCode = new javax.swing.JComboBox();
        Date = new javax.swing.JComboBox();
        Month = new javax.swing.JComboBox();
        year = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        Month1 = new javax.swing.JComboBox();
        Date1 = new javax.swing.JComboBox();
        year1 = new javax.swing.JComboBox();
        ReportLBL = new javax.swing.JLabel();
        ContinueBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        BookingDetailsPart2Panel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        AddressTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        MaleRB = new javax.swing.JRadioButton();
        FemaleRB = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        AgeTF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ArrivalTF = new javax.swing.JTextField();
        DepartureTF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        AdvanceTF = new javax.swing.JTextField();
        RNoLBL = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        totalChargesLBL = new javax.swing.JLabel();
        BookBTN = new javax.swing.JButton();
        bookCancelMnuBar = new javax.swing.JMenuBar();
        editMnu = new javax.swing.JMenu();
        edit_BookMItem = new javax.swing.JMenuItem();
        edit_CancelMItem = new javax.swing.JMenuItem();
        BackMnu = new javax.swing.JMenu();
        back_MainMItem = new javax.swing.JMenuItem();
        back_LogoutMItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BOOKING/CANCELLATION");

        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        mainPanel.setMaximumSize(new java.awt.Dimension(214747, 214647));
        mainPanel.setLayout(new java.awt.CardLayout());

        bookCancelOptionsPanel.setBackground(new java.awt.Color(102, 255, 102));

        CancelBooking.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CancelBooking.setText("<HTML>Cancel<br>Booking</HTML>");
        CancelBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBookingActionPerformed(evt);
            }
        });

        Back.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Booking.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Booking.setText("<HTML>Make<br>Booking</HTML>");
        Booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingActionPerformed(evt);
            }
        });
        Booking.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                BookingFocusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setText("BOOKING/CANCELLATION");

        javax.swing.GroupLayout bookCancelOptionsPanelLayout = new javax.swing.GroupLayout(bookCancelOptionsPanel);
        bookCancelOptionsPanel.setLayout(bookCancelOptionsPanelLayout);
        bookCancelOptionsPanelLayout.setHorizontalGroup(
            bookCancelOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookCancelOptionsPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(bookCancelOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Back, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Booking, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CancelBooking, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        bookCancelOptionsPanelLayout.setVerticalGroup(
            bookCancelOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookCancelOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(Booking, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(CancelBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        mainPanel.add(bookCancelOptionsPanel, "card5");

        cancelBookingPanel.setMaximumSize(new java.awt.Dimension(367, 367));
        cancelBookingPanel.setPreferredSize(new java.awt.Dimension(87, 104));

        continueBtn.setText("Continue..");
        continueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ENTER BOOKING NUMBER");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        error1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        error1.setText("           ");
        error1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cancelBtn.setText("Cancel Booking");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TO CANCEL BOOKING");

        javax.swing.GroupLayout cancelBookingPanelLayout = new javax.swing.GroupLayout(cancelBookingPanel);
        cancelBookingPanel.setLayout(cancelBookingPanelLayout);
        cancelBookingPanelLayout.setHorizontalGroup(
            cancelBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelBookingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancelBookingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancelBookingPanelLayout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(BookingNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancelBookingPanelLayout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addComponent(continueBtn)
                .addGap(160, 160, 160))
            .addGroup(cancelBookingPanelLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(cancelBtn)
                .addContainerGap(153, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancelBookingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(error1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
        );
        cancelBookingPanelLayout.setVerticalGroup(
            cancelBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancelBookingPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(36, 36, 36)
                .addComponent(BookingNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(continueBtn)
                .addGap(18, 18, 18)
                .addComponent(error1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(cancelBtn)
                .addGap(34, 34, 34))
        );

        mainPanel.add(cancelBookingPanel, "card3");

        EnterBookingDetailsPanel.setMaximumSize(new java.awt.Dimension(277, 200));
        EnterBookingDetailsPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        EnterBookingDetailsPanel.setPreferredSize(new java.awt.Dimension(228, 200));

        jLabel2.setText("Room Type: ");

        jLabel3.setText("Arrival:");

        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        TCode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SN", "DB", "DL", "SD" }));

        Date.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01" }));

        Month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01" }));
        Month.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MonthItemStateChanged(evt);
            }
        });

        year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2010", "2011", "2012" }));

        jLabel9.setText("Departure:");

        Month1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01" }));
        Month1.setSelectedItem(01);
        Month1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Month1ItemStateChanged(evt);
            }
        });

        Date1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01" }));

        year1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2010", "2011", "2012" }));

        ReportLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReportLBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ContinueBtn.setText("Continue..");
        ContinueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16));
        jLabel4.setText("ENTER BOOKING DETAILS");

        javax.swing.GroupLayout EnterBookingDetailsPanelLayout = new javax.swing.GroupLayout(EnterBookingDetailsPanel);
        EnterBookingDetailsPanel.setLayout(EnterBookingDetailsPanelLayout);
        EnterBookingDetailsPanelLayout.setHorizontalGroup(
            EnterBookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnterBookingDetailsPanelLayout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addComponent(ContinueBtn)
                .addGap(145, 145, 145))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnterBookingDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ReportLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(EnterBookingDetailsPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(EnterBookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EnterBookingDetailsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(63, 63, 63)
                        .addComponent(TCode, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnterBookingDetailsPanelLayout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(SearchBtn)
                .addGap(158, 158, 158))
            .addGroup(EnterBookingDetailsPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(EnterBookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EnterBookingDetailsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(31, 31, 31)
                        .addComponent(Month1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Date1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(year1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EnterBookingDetailsPanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        EnterBookingDetailsPanelLayout.setVerticalGroup(
            EnterBookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnterBookingDetailsPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addGroup(EnterBookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TCode, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(EnterBookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EnterBookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(Month1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(SearchBtn)
                .addGap(13, 13, 13)
                .addComponent(ReportLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ContinueBtn)
                .addContainerGap())
        );

        mainPanel.add(EnterBookingDetailsPanel, "card2");

        BookingDetailsPart2Panel.setEnabled(false);

        jLabel8.setText("Room No.");

        jLabel10.setText("Name");

        jLabel11.setText("Address");

        jLabel12.setText("Sex");

        buttonGroup1.add(MaleRB);
        MaleRB.setText("Male");

        buttonGroup1.add(FemaleRB);
        FemaleRB.setText("Female");

        jLabel13.setText("Age");

        jLabel14.setText("Arrival:");

        jLabel15.setText("Departure:");

        ArrivalTF.setEnabled(false);

        DepartureTF.setEnabled(false);

        jLabel16.setText("Advance");

        RNoLBL.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel18.setText("Charges: ");

        totalChargesLBL.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BookBTN.setFont(new java.awt.Font("Tahoma", 1, 24));
        BookBTN.setText("BOOK");
        BookBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BookingDetailsPart2PanelLayout = new javax.swing.GroupLayout(BookingDetailsPart2Panel);
        BookingDetailsPart2Panel.setLayout(BookingDetailsPart2PanelLayout);
        BookingDetailsPart2PanelLayout.setHorizontalGroup(
            BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingDetailsPart2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingDetailsPart2PanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(10, 10, 10)
                        .addComponent(RNoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalChargesLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(BookingDetailsPart2PanelLayout.createSequentialGroup()
                        .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BookingDetailsPart2PanelLayout.createSequentialGroup()
                                .addComponent(AddressTF, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(BookingDetailsPart2PanelLayout.createSequentialGroup()
                                    .addComponent(nameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                    .addGap(97, 97, 97))
                                .addGroup(BookingDetailsPart2PanelLayout.createSequentialGroup()
                                    .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(AgeTF, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(AdvanceTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                        .addComponent(DepartureTF, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ArrivalTF, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                    .addComponent(BookBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(45, 45, 45))
                                .addGroup(BookingDetailsPart2PanelLayout.createSequentialGroup()
                                    .addComponent(MaleRB)
                                    .addGap(34, 34, 34)
                                    .addComponent(FemaleRB)
                                    .addContainerGap(184, Short.MAX_VALUE)))))))
        );
        BookingDetailsPart2PanelLayout.setVerticalGroup(
            BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingDetailsPart2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(RNoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(totalChargesLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingDetailsPart2PanelLayout.createSequentialGroup()
                        .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(MaleRB)
                            .addComponent(FemaleRB))
                        .addGap(18, 18, 18)
                        .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AgeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ArrivalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DepartureTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AdvanceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingDetailsPart2PanelLayout.createSequentialGroup()
                        .addComponent(BookBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );

        mainPanel.add(BookingDetailsPart2Panel, "card4");

        bookCancelMnuBar.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        bookCancelMnuBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        editMnu.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        editMnu.setText("Edit");
        editMnu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editMnu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editMnu.setPreferredSize(new java.awt.Dimension(50, 19));

        edit_BookMItem.setText("Book");
        edit_BookMItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_BookMItemActionPerformed(evt);
            }
        });
        editMnu.add(edit_BookMItem);

        edit_CancelMItem.setText("Cancel");
        edit_CancelMItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_CancelMItemActionPerformed(evt);
            }
        });
        editMnu.add(edit_CancelMItem);

        bookCancelMnuBar.add(editMnu);

        BackMnu.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        BackMnu.setText("Back");
        BackMnu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BackMnu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BackMnu.setPreferredSize(new java.awt.Dimension(50, 19));

        back_MainMItem.setText("Main Menu");
        back_MainMItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_MainMItemActionPerformed(evt);
            }
        });
        BackMnu.add(back_MainMItem);

        back_LogoutMItem.setText("Logout");
        back_LogoutMItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_LogoutMItemActionPerformed(evt);
            }
        });
        BackMnu.add(back_LogoutMItem);

        bookCancelMnuBar.add(BackMnu);

        setJMenuBar(bookCancelMnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBookingActionPerformed
        // TODO add your handling code here:
        EnterBookingDetailsPanel.setVisible(false);
        BookingDetailsPart2Panel.setVisible(false);
        bookCancelOptionsPanel.setVisible(false);
        cancelBookingPanel.setVisible(true);
}//GEN-LAST:event_CancelBookingActionPerformed

    private void BookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingActionPerformed
        // TODO add your handling code here:
        BookingDetailsPart2Panel.setVisible(false);
        cancelBookingPanel.setVisible(false);
        bookCancelOptionsPanel.setVisible(false);
        EnterBookingDetailsPanel.setVisible(true);
}//GEN-LAST:event_BookingActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        MainMenu m = new MainMenu();
        m.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_BackActionPerformed
    private int getmax(int month1 ,int month2, int d2)
    { 
        if(month1 == month2)
            return d2;
        else if(month1 == 2)
            return 28;
        else if(month1==4 || month1==6 || month1==9 || month1==11)
            return 30;
        else
            return 31;
    }
    private int search(int month, int month2, int day1, int day2, String Tcode)
    {
        String avail="f";
        boolean found = false;
        int rNo = 0;
        int max = getmax(month,month2,day2);
        try {
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost:3306/Hotel";
            Connection conn = DriverManager.getConnection(database, "root", "root");
            Statement stmt = conn.createStatement();
            String sql = "select * from Status" + month + " where TypeCode = '" + Tcode + "'";
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next())
            {
               int i;
               for(i=day1; i<=max; i++)
               {
                   avail = rs.getString(i+2);
                                               
                   if (avail.equals("b") || avail.equals("o"))
                       break;
               }
               if(i == max+1)
               {
                   rNo = rs.getInt(1);
                   if(month != month2)
                    found = search2(month+1,month2,1,day2,Tcode,rNo);
                   else
                       break;
                    if(found)
                       break;
               }
           }
           rs.close();
           stmt.close();
           conn.close();
        } catch (Exception e) { ReportLBL.setText("Incorrect Entry" + e);}
        return rNo;
    }
    private boolean search2(int month1 , int month2,int day1,int day2, String Tcode , int rno)
    {
        String avail="f";
        boolean found = false;
        int rNo = 0;
        int max = getmax(month1,month2,day2);
        try {
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost:3306/Hotel";
            Connection conn = DriverManager.getConnection(database, "root", "root");
            Statement stmt = conn.createStatement();
            String sql = "select * from status" + month1 + " where TypeCode = '" + Tcode + "' and RoomNo = " + rno;
            ResultSet rs = stmt.executeQuery(sql);
            rs.next();
               int i;
               for(i=day1; i<=max; i++)
               {
                   avail = rs.getString(i+2);
                   if (avail.equals("b") || avail.equals("o"))
                       break;
               }
               if(i == max+1)
               {
                   if(month1 != month2)
                    found = search2(month1+1,month2,1,day2,Tcode,rNo);
                   else
                       return true;
               }
               rs.close();
               stmt.close();
               conn.close();
        } catch (Exception e) { ReportLBL.setText("Incorrect Entry");}
        return found;
    }
    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
        ReportLBL.setText("  ");
        boolean found = false;
        ContinueBtn.setVisible(false);
        int roomNo=0;
        int month = Integer.parseInt(Month.getSelectedItem().toString());
        aMonth=month;
        int month2 = Integer.parseInt(Month1.getSelectedItem().toString());
        dMonth=month2;
        int day1 = Integer.parseInt(Date.getSelectedItem().toString());
        aDay=day1;
        int day2 = Integer.parseInt(Date1.getSelectedItem().toString());
        dDay=day2;
        char avail = 'n';
        String Tcode = TCode.getSelectedItem().toString();
         roomNo = search(month,month2,day1,day2,Tcode);   
        if(roomNo ==0)
            ReportLBL.setText("No Room available.");
           else
           {
                   ReportLBL.setText("Room No. " + roomNo + " is Available. Click continue to book the room.");
                   ContinueBtn.setVisible(true);
                   RNoLBL.setText(roomNo +"");
                   ArrivalTF.setText("2010" +"/"+month + "/" + day1);
                   DepartureTF.setText("2010" +"/"+month2 + "/" + day2);
           }
         Calendar c = Calendar.getInstance();
         c.set(2010,month,day1);
         Calendar c2 = Calendar.getInstance();
         c2.set(2010,month2,day2);
         stayTime = (int)((c2.getTimeInMillis() - c.getTimeInMillis())/(1000*60*60*24));
}//GEN-LAST:event_SearchBtnActionPerformed

    private void continueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueBtnActionPerformed
        // TODO add your handling code here:
        cancelBtn.setVisible(false);
        int bno =Integer.parseInt( BookingNoTF.getText());
        try {
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost:3306/Hotel";
            Connection conn = DriverManager.getConnection(database, "root", "root");
            Statement stmt = conn.createStatement();
            String sql = "select RoomNo, FromD, ToD from Booking where BookingNo = " + bno ;
            ResultSet rs = stmt.executeQuery(sql);
            if(rs.next())
            {
               int rno = rs.getInt("RoomNo");
               Calendar c = Calendar.getInstance();
               Calendar c2 = Calendar.getInstance();
               c.setTime(rs.getDate(2));
               c2.setTime(rs.getDate(3));
               int month1 = c.get(Calendar.MONTH) + 1;
               int month2 = c2.get(Calendar.MONTH) + 1;
               int day1 = c.get(Calendar.DATE);
               int day2 = c2.get(Calendar.DATE);
               while(month1<=month2)
                {
                   int max=getmax(month1,month2,day2);
                   int min=0;
                   if(month1==month2)
                      min=day1;
                  else
                     min=1;
                  for(int d=min;d<=max;d++)
                  {
                      String sql3 = "update Status" + month1 + " set D" + d + " = 'f' where RoomNo = " + rno;
                      stmt.executeUpdate(sql3);
                  }
                  month1++;
               }
               error1.setText("Click continue to genrate calcelation slip");
               cancelBtn.setVisible(true);
            }
            else
            {
                error1.setText("Unable to find booking number");
            }
            stmt.close();
            conn.close();
        } catch (Exception e) { error1.setText("Unable to find booking number");
            JOptionPane.showMessageDialog(null,"Invalid Data" + e);
        }
}//GEN-LAST:event_continueBtnActionPerformed

    private void BookingFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BookingFocusLost
        // TODO add your handling code here:
}//GEN-LAST:event_BookingFocusLost

    private void MonthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MonthItemStateChanged
        // TODO add your handling code here:
        Date.removeAllItems();
         String m="0";
        int mon =0,days=0;
        int yr = Integer.parseInt(year.getSelectedItem().toString());
        if(Month.getSelectedIndex()>=1)
        {
            mon = Integer.parseInt(Month.getSelectedItem().toString());
        }
        if(mon==2)
          if(yr%4 != 0)
            days = 28;
          else
              days =29;
        else if( mon==4 || mon ==6 || mon==9 || mon==11)
             days = 30;
        else
            days = 31;
        for(int i =1; i<=days ;i++)
        {
            if(i>9)
                m="";
            Date.addItem(m+i);
        }
    }//GEN-LAST:event_MonthItemStateChanged

    private void Month1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Month1ItemStateChanged
               Date1.removeAllItems();
         String m="0";
        int mon =0,days=0;
        int yr = Integer.parseInt(year1.getSelectedItem().toString());
        if(Month1.getSelectedIndex()>=1)
        {
            mon = Integer.parseInt(Month1.getSelectedItem().toString());
        }
        if(mon==2)
          if(yr%4 != 0)
            days = 28;
          else
              days =29;
        else if( mon==4 || mon ==6 || mon==9 || mon==11)
             days = 30;
        else
            days = 31;
        for(int i =1; i<=days ;i++)
        {
            if(i>9)
                m="";
            Date1.addItem(m+i);
        }
    }//GEN-LAST:event_Month1ItemStateChanged

    private void ContinueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueBtnActionPerformed
        // TODO add your handling code here:
        String code = TCode.getSelectedItem().toString();
        try {
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost:3306/Hotel";
            Connection conn = DriverManager.getConnection(database, "root", "root");
            Statement stmt = conn.createStatement();
            String sql = "select Charges from Type where TypeCode = '" + code + "'";
            ResultSet rs = stmt.executeQuery(sql);
            rs.next();
            int charge = rs.getInt("Charges");
            charge = charge * stayTime;
            totalChargesLBL.setText(charge+"");
            rs.close();
            stmt.close();
            conn.close();
        } catch (Exception e) { }
        EnterBookingDetailsPanel.setVisible(false);
        cancelBookingPanel.setVisible(false);
        BookingDetailsPart2Panel.setVisible(true);
}//GEN-LAST:event_ContinueBtnActionPerformed

    private void BookBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookBTNActionPerformed
        // TODO add your handling code here:
        char gender = 'n';
        int month=aMonth;
        if(MaleRB.isSelected())
            gender = 'm';
        else if(FemaleRB.isSelected())
            gender = 'f';
        int age = Integer.parseInt(AgeTF.getText());
        int rno =Integer.parseInt(RNoLBL.getText());
        int advance =Integer.parseInt(AdvanceTF.getText());
        int tot =Integer.parseInt(totalChargesLBL.getText());
        try
        {
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost:3306/Hotel";
            Connection conn = DriverManager.getConnection(database, "root", "root");
            Statement stmt2 = conn.createStatement();
            String sql2 = "Select max(BookingNo) from Booking";
            ResultSet rs = stmt2.executeQuery(sql2);
            rs.next();
            int bno = rs.getInt(1)+1;
           Statement stmt = conn.createStatement();
           String sql = "insert into Booking values (" + bno + ", '" + nameTF.getText() + "' , '" + AddressTF.getText() + "' , '" + gender + "' , "+ age + " , " + rno + " , '" + ArrivalTF.getText() + "' , '" + DepartureTF.getText() + "' , " + advance + " , " + tot + " )" ;
           stmt.executeUpdate(sql);
           while(month<=dMonth)
           {
               int max=getmax(month,dMonth,dDay);
               int min=0;
               if(month==aMonth)
                    min=aDay;
               else
                     min=1;
               for(int d=min;d<=max;d++)
               {
                  String sql3 = "update status" + month + " set D" + d + " = 'b' where RoomNo = " + rno;
                  stmt.executeUpdate(sql3);
               }
               month++;
            }
            JOptionPane.showMessageDialog(null,"Room booked. Booking number is: "+ bno);
            stmt.close();
            stmt2.close();
            conn.close();
            new ReservaTionSlip(bno).setVisible(true);
            this.setVisible(false);
        }
catch (Exception e) { JOptionPane.showMessageDialog(null,"Invalid Data" + e); }
}//GEN-LAST:event_BookBTNActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        int bookingNo =Integer.parseInt( BookingNoTF.getText());
        new CancellationSlip(bookingNo).setVisible(true);
        this.setVisible(false);

}//GEN-LAST:event_cancelBtnActionPerformed

    private void back_MainMItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_MainMItemActionPerformed
        // TODO add your handling code here:
        MainMenu m = new MainMenu();
        m.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_back_MainMItemActionPerformed

    private void back_LogoutMItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_LogoutMItemActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_back_LogoutMItemActionPerformed

    private void edit_BookMItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_BookMItemActionPerformed
        BookingDetailsPart2Panel.setVisible(false);
        cancelBookingPanel.setVisible(false);
        bookCancelOptionsPanel.setVisible(false);
        EnterBookingDetailsPanel.setVisible(true);
}//GEN-LAST:event_edit_BookMItemActionPerformed

    private void edit_CancelMItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_CancelMItemActionPerformed
        EnterBookingDetailsPanel.setVisible(false);
        BookingDetailsPart2Panel.setVisible(false);
        bookCancelOptionsPanel.setVisible(false);
        cancelBookingPanel.setVisible(true);
}//GEN-LAST:event_edit_CancelMItemActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookCancel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTF;
    private javax.swing.JTextField AdvanceTF;
    private javax.swing.JTextField AgeTF;
    private javax.swing.JTextField ArrivalTF;
    private javax.swing.JButton Back;
    private javax.swing.JMenu BackMnu;
    private javax.swing.JButton BookBTN;
    private javax.swing.JButton Booking;
    private javax.swing.JPanel BookingDetailsPart2Panel;
    private javax.swing.JTextField BookingNoTF;
    private javax.swing.JButton CancelBooking;
    private javax.swing.JButton ContinueBtn;
    private javax.swing.JComboBox Date;
    private javax.swing.JComboBox Date1;
    private javax.swing.JTextField DepartureTF;
    private javax.swing.JPanel EnterBookingDetailsPanel;
    private javax.swing.JRadioButton FemaleRB;
    private javax.swing.JRadioButton MaleRB;
    private javax.swing.JComboBox Month;
    private javax.swing.JComboBox Month1;
    private javax.swing.JLabel RNoLBL;
    private javax.swing.JLabel ReportLBL;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JComboBox TCode;
    private javax.swing.JMenuItem back_LogoutMItem;
    private javax.swing.JMenuItem back_MainMItem;
    private javax.swing.JMenuBar bookCancelMnuBar;
    private javax.swing.JPanel bookCancelOptionsPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cancelBookingPanel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton continueBtn;
    private javax.swing.JMenu editMnu;
    private javax.swing.JMenuItem edit_BookMItem;
    private javax.swing.JMenuItem edit_CancelMItem;
    private javax.swing.JLabel error1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel totalChargesLBL;
    private javax.swing.JComboBox year;
    private javax.swing.JComboBox year1;
    // End of variables declaration//GEN-END:variables

}
