create database Hotel;
use Hotel;
create table LogIn(
ID varchar(20) primary key,
Password varchar (20) Not null);

Create table Status1(
RoomNo integer(11) Primary key,
Typecode char(20) not null,
D1 char(1) not null default 'f',
D2 char(1) not null default 'f',
D3 char(1) not null default 'f',
D4 char(1) not null default 'f',
D5 char(1) not null default 'f',
D6 char(1) not null default 'f',
D7 char(1) not null default 'f',
D8 char(1) not null default 'f',
D9 char(1) not null default 'f',
D10 char(1) not null default 'f',
D11 char(1) not null default 'f',
D12 char(1) not null default 'f',
D13 char(1) not null default 'f',
D14 char(1) not null default 'f',
D15 char(1) not null  default 'f',
D16 char(1) not null default 'f',
D17 char(1) not null default 'f',
D18 char(1) not null default 'f',
D19 char(1) not null default 'f',
D20 char(1) not null default 'f',
D21 char(1) not null default 'f',
D22 char(1) not null default 'f',
D23 char(1) not null default 'f',
D24 char(1) not null default 'f',
D25 char(1) not null default 'f',
D26 char(1) not null default 'f',
D27 char(1) not null default 'f',
D28 char(1) not null default 'f',
D29 char(1) not null default 'f',
D30 char(1) not null default 'f',
D31 char(11) not null default 'f'
);
Create table Status2(
RoomNo integer(11) Primary key,
Typecode char(20) not null,
D1 char(1) not null default 'f',
D2 char(1) not null default 'f',
D3 char(1) not null default 'f',
D4 char(1) not null default 'f',
D5 char(1) not null default 'f',
D6 char(1) not null default 'f',
D7 char(1) not null default 'f',
D8 char(1) not null default 'f',
D9 char(1) not null default 'f',
D10 char(1) not null default 'f',
D11 char(1) not null default 'f',
D12 char(1) not null default 'f',
D13 char(1) not null default 'f',
D14 char(1) not null default 'f',
D15 char(1) not null  default 'f',
D16 char(1) not null default 'f',
D17 char(1) not null default 'f',
D18 char(1) not null default 'f',
D19 char(1) not null default 'f',
D20 char(1) not null default 'f',
D21 char(1) not null default 'f',
D22 char(1) not null default 'f',
D23 char(1) not null default 'f',
D24 char(1) not null default 'f',
D25 char(1) not null default 'f',
D26 char(1) not null default 'f',
D27 char(1) not null default 'f',
D28 char(1) not null default 'f',
D29 char(1) not null default 'f',
D30 char(1) not null default 'f',
D31 char(11) not null default 'f'
);

Create table Status3(
RoomNo integer(11) Primary key,
Typecode char(20) not null,
D1 char(1) not null default 'f',
D2 char(1) not null default 'f',
D3 char(1) not null default 'f',
D4 char(1) not null default 'f',
D5 char(1) not null default 'f',
D6 char(1) not null default 'f',
D7 char(1) not null default 'f',
D8 char(1) not null default 'f',
D9 char(1) not null default 'f',
D10 char(1) not null default 'f',
D11 char(1) not null default 'f',
D12 char(1) not null default 'f',
D13 char(1) not null default 'f',
D14 char(1) not null default 'f',
D15 char(1) not null  default 'f',
D16 char(1) not null default 'f',
D17 char(1) not null default 'f',
D18 char(1) not null default 'f',
D19 char(1) not null default 'f',
D20 char(1) not null default 'f',
D21 char(1) not null default 'f',
D22 char(1) not null default 'f',
D23 char(1) not null default 'f',
D24 char(1) not null default 'f',
D25 char(1) not null default 'f',
D26 char(1) not null default 'f',
D27 char(1) not null default 'f',
D28 char(1) not null default 'f',
D29 char(1) not null default 'f',
D30 char(1) not null default 'f',
D31 char(11) not null default 'f'
);
Create table Status4(
RoomNo integer(11) Primary key,
Typecode char(20) not null,
D1 char(1) not null default 'f',
D2 char(1) not null default 'f',
D3 char(1) not null default 'f',
D4 char(1) not null default 'f',
D5 char(1) not null default 'f',
D6 char(1) not null default 'f',
D7 char(1) not null default 'f',
D8 char(1) not null default 'f',
D9 char(1) not null default 'f',
D10 char(1) not null default 'f',
D11 char(1) not null default 'f',
D12 char(1) not null default 'f',
D13 char(1) not null default 'f',
D14 char(1) not null default 'f',
D15 char(1) not null  default 'f',
D16 char(1) not null default 'f',
D17 char(1) not null default 'f',
D18 char(1) not null default 'f',
D19 char(1) not null default 'f',
D20 char(1) not null default 'f',
D21 char(1) not null default 'f',
D22 char(1) not null default 'f',
D23 char(1) not null default 'f',
D24 char(1) not null default 'f',
D25 char(1) not null default 'f',
D26 char(1) not null default 'f',
D27 char(1) not null default 'f',
D28 char(1) not null default 'f',
D29 char(1) not null default 'f',
D30 char(1) not null default 'f',
D31 char(11) not null default 'f'
);
Create table Status5(
RoomNo integer(11) Primary key,
Typecode char(20) not null,
D1 char(1) not null default 'f',
D2 char(1) not null default 'f',
D3 char(1) not null default 'f',
D4 char(1) not null default 'f',
D5 char(1) not null default 'f',
D6 char(1) not null default 'f',
D7 char(1) not null default 'f',
D8 char(1) not null default 'f',
D9 char(1) not null default 'f',
D10 char(1) not null default 'f',
D11 char(1) not null default 'f',
D12 char(1) not null default 'f',
D13 char(1) not null default 'f',
D14 char(1) not null default 'f',
D15 char(1) not null  default 'f',
D16 char(1) not null default 'f',
D17 char(1) not null default 'f',
D18 char(1) not null default 'f',
D19 char(1) not null default 'f',
D20 char(1) not null default 'f',
D21 char(1) not null default 'f',
D22 char(1) not null default 'f',
D23 char(1) not null default 'f',
D24 char(1) not null default 'f',
D25 char(1) not null default 'f',
D26 char(1) not null default 'f',
D27 char(1) not null default 'f',
D28 char(1) not null default 'f',
D29 char(1) not null default 'f',
D30 char(1) not null default 'f',
D31 char(11) not null default 'f'
);
Create table Status6(
RoomNo integer(11) Primary key,
Typecode char(20) not null,
D1 char(1) not null default 'f',
D2 char(1) not null default 'f',
D3 char(1) not null default 'f',
D4 char(1) not null default 'f',
D5 char(1) not null default 'f',
D6 char(1) not null default 'f',
D7 char(1) not null default 'f',
D8 char(1) not null default 'f',
D9 char(1) not null default 'f',
D10 char(1) not null default 'f',
D11 char(1) not null default 'f',
D12 char(1) not null default 'f',
D13 char(1) not null default 'f',
D14 char(1) not null default 'f',
D15 char(1) not null  default 'f',
D16 char(1) not null default 'f',
D17 char(1) not null default 'f',
D18 char(1) not null default 'f',
D19 char(1) not null default 'f',
D20 char(1) not null default 'f',
D21 char(1) not null default 'f',
D22 char(1) not null default 'f',
D23 char(1) not null default 'f',
D24 char(1) not null default 'f',
D25 char(1) not null default 'f',
D26 char(1) not null default 'f',
D27 char(1) not null default 'f',
D28 char(1) not null default 'f',
D29 char(1) not null default 'f',
D30 char(1) not null default 'f',
D31 char(11) not null default 'f'
);
Create table Status7(
RoomNo integer(11) Primary key,
Typecode char(20) not null,
D1 char(1) not null default 'f',
D2 char(1) not null default 'f',
D3 char(1) not null default 'f',
D4 char(1) not null default 'f',
D5 char(1) not null default 'f',
D6 char(1) not null default 'f',
D7 char(1) not null default 'f',
D8 char(1) not null default 'f',
D9 char(1) not null default 'f',
D10 char(1) not null default 'f',
D11 char(1) not null default 'f',
D12 char(1) not null default 'f',
D13 char(1) not null default 'f',
D14 char(1) not null default 'f',
D15 char(1) not null  default 'f',
D16 char(1) not null default 'f',
D17 char(1) not null default 'f',
D18 char(1) not null default 'f',
D19 char(1) not null default 'f',
D20 char(1) not null default 'f',
D21 char(1) not null default 'f',
D22 char(1) not null default 'f',
D23 char(1) not null default 'f',
D24 char(1) not null default 'f',
D25 char(1) not null default 'f',
D26 char(1) not null default 'f',
D27 char(1) not null default 'f',
D28 char(1) not null default 'f',
D29 char(1) not null default 'f',
D30 char(1) not null default 'f',
D31 char(11) not null default 'f'
);
Create table Status8(
RoomNo integer(11) Primary key,
Typecode char(20) not null,
D1 char(1) not null default 'f',
D2 char(1) not null default 'f',
D3 char(1) not null default 'f',
D4 char(1) not null default 'f',
D5 char(1) not null default 'f',
D6 char(1) not null default 'f',
D7 char(1) not null default 'f',
D8 char(1) not null default 'f',
D9 char(1) not null default 'f',
D10 char(1) not null default 'f',
D11 char(1) not null default 'f',
D12 char(1) not null default 'f',
D13 char(1) not null default 'f',
D14 char(1) not null default 'f',
D15 char(1) not null  default 'f',
D16 char(1) not null default 'f',
D17 char(1) not null default 'f',
D18 char(1) not null default 'f',
D19 char(1) not null default 'f',
D20 char(1) not null default 'f',
D21 char(1) not null default 'f',
D22 char(1) not null default 'f',
D23 char(1) not null default 'f',
D24 char(1) not null default 'f',
D25 char(1) not null default 'f',
D26 char(1) not null default 'f',
D27 char(1) not null default 'f',
D28 char(1) not null default 'f',
D29 char(1) not null default 'f',
D30 char(1) not null default 'f',
D31 char(11) not null default 'f'
);
Create table Status9(
RoomNo integer(11) Primary key,
Typecode char(20) not null,
D1 char(1) not null default 'f',
D2 char(1) not null default 'f',
D3 char(1) not null default 'f',
D4 char(1) not null default 'f',
D5 char(1) not null default 'f',
D6 char(1) not null default 'f',
D7 char(1) not null default 'f',
D8 char(1) not null default 'f',
D9 char(1) not null default 'f',
D10 char(1) not null default 'f',
D11 char(1) not null default 'f',
D12 char(1) not null default 'f',
D13 char(1) not null default 'f',
D14 char(1) not null default 'f',
D15 char(1) not null  default 'f',
D16 char(1) not null default 'f',
D17 char(1) not null default 'f',
D18 char(1) not null default 'f',
D19 char(1) not null default 'f',
D20 char(1) not null default 'f',
D21 char(1) not null default 'f',
D22 char(1) not null default 'f',
D23 char(1) not null default 'f',
D24 char(1) not null default 'f',
D25 char(1) not null default 'f',
D26 char(1) not null default 'f',
D27 char(1) not null default 'f',
D28 char(1) not null default 'f',
D29 char(1) not null default 'f',
D30 char(1) not null default 'f',
D31 char(11) not null default 'f'
);
Create table Status10(
RoomNo integer(11) Primary key,
Typecode char(20) not null,
D1 char(1) not null default 'f',
D2 char(1) not null default 'f',
D3 char(1) not null default 'f',
D4 char(1) not null default 'f',
D5 char(1) not null default 'f',
D6 char(1) not null default 'f',
D7 char(1) not null default 'f',
D8 char(1) not null default 'f',
D9 char(1) not null default 'f',
D10 char(1) not null default 'f',
D11 char(1) not null default 'f',
D12 char(1) not null default 'f',
D13 char(1) not null default 'f',
D14 char(1) not null default 'f',
D15 char(1) not null  default 'f',
D16 char(1) not null default 'f',
D17 char(1) not null default 'f',
D18 char(1) not null default 'f',
D19 char(1) not null default 'f',
D20 char(1) not null default 'f',
D21 char(1) not null default 'f',
D22 char(1) not null default 'f',
D23 char(1) not null default 'f',
D24 char(1) not null default 'f',
D25 char(1) not null default 'f',
D26 char(1) not null default 'f',
D27 char(1) not null default 'f',
D28 char(1) not null default 'f',
D29 char(1) not null default 'f',
D30 char(1) not null default 'f',
D31 char(11) not null default 'f'
);
Create table Status11(
RoomNo integer(11) Primary key,
Typecode char(20) not null,
D1 char(1) not null default 'f',
D2 char(1) not null default 'f',
D3 char(1) not null default 'f',
D4 char(1) not null default 'f',
D5 char(1) not null default 'f',
D6 char(1) not null default 'f',
D7 char(1) not null default 'f',
D8 char(1) not null default 'f',
D9 char(1) not null default 'f',
D10 char(1) not null default 'f',
D11 char(1) not null default 'f',
D12 char(1) not null default 'f',
D13 char(1) not null default 'f',
D14 char(1) not null default 'f',
D15 char(1) not null  default 'f',
D16 char(1) not null default 'f',
D17 char(1) not null default 'f',
D18 char(1) not null default 'f',
D19 char(1) not null default 'f',
D20 char(1) not null default 'f',
D21 char(1) not null default 'f',
D22 char(1) not null default 'f',
D23 char(1) not null default 'f',
D24 char(1) not null default 'f',
D25 char(1) not null default 'f',
D26 char(1) not null default 'f',
D27 char(1) not null default 'f',
D28 char(1) not null default 'f',
D29 char(1) not null default 'f',
D30 char(1) not null default 'f',
D31 char(11) not null default 'f'
);
Create table Status12(
RoomNo integer(11) Primary key,
Typecode char(20) not null,
D1 char(1) not null default 'f',
D2 char(1) not null default 'f',
D3 char(1) not null default 'f',
D4 char(1) not null default 'f',
D5 char(1) not null default 'f',
D6 char(1) not null default 'f',
D7 char(1) not null default 'f',
D8 char(1) not null default 'f',
D9 char(1) not null default 'f',
D10 char(1) not null default 'f',
D11 char(1) not null default 'f',
D12 char(1) not null default 'f',
D13 char(1) not null default 'f',
D14 char(1) not null default 'f',
D15 char(1) not null  default 'f',
D16 char(1) not null default 'f',
D17 char(1) not null default 'f',
D18 char(1) not null default 'f',
D19 char(1) not null default 'f',
D20 char(1) not null default 'f',
D21 char(1) not null default 'f',
D22 char(1) not null default 'f',
D23 char(1) not null default 'f',
D24 char(1) not null default 'f',
D25 char(1) not null default 'f',
D26 char(1) not null default 'f',
D27 char(1) not null default 'f',
D28 char(1) not null default 'f',
D29 char(1) not null default 'f',
D30 char(1) not null default 'f',
D31 char(11) not null default 'f'
);


Create table Booking(
BookingNo integer(11) Primary key not null,
CustName varchar(20) ,
Address varchar(30),
Sex varchar(1),
Age int(11) ,
RoomNo int(11),
FromD date ,
ToD date ,
Advance int(11) ,
Total int(11) );

Create table Room(
RoomNo int(11) primary key,
TypeCode varchar(2) not null);

Create table Type(
TypeCode char(2) primary key,
Description varchar(20) Not null,
charges int(11) not null);


insert into Type
values('SN','Supre Nova',10000);

insert into Type
values('SD','Super Deluxe',15000);
insert into Type
values('DL','Deluxe Lounge',20000);
insert into Type
values('DB','Deluxe Beds',25000);

insert into LogIn values 
('puneet',1234);
